---

- name: "Set {{ developer_user.key }} presence flag"
  set_fact:
    is_present: "{{ developer_user.value.state | default('present') == 'present' }}"

- name: "Copy {{ developer_user.key }} nctl configuration"
  become: True
  synchronize:
    src: "/usr/local/bin/config"
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}"
  when: is_present

- name: "Copy default packs to {{ developer_user.key }} user directory according to infrastructure"
  become: True
  synchronize:
    src: "{{ nauta_admin_home }}/packs/gcp/{{ pool_type }}/packs"
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}/config"
  when: is_present and (pool_type | default('')) != ""

- name: "Fix {{ developer_user.key }} fresh nctl configuration ownership"
  become: True
  file:
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}/config"
    owner: "{{ developer_user.key }}"
    group: "{{ worker_groupname }}"
    recurse: True

- name: "Copy {{ developer_user.key }} nctl examples"
  become: True
  synchronize:
    src: "/usr/local/bin/examples"
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}"
  when: is_present

- name: "Fix {{ developer_user.key }} fresh nctl examples ownership"
  become: True
  file:
    dest: "{{ worker_home_prefix }}/{{ developer_user.key }}/examples"
    owner: "{{ developer_user.key }}"
    group: "{{ worker_groupname }}"
    recurse: True
