---

proxy:
  http_proxy: "{{ lookup('env','http_proxy') }}"
  HTTP_PROXY: "{{ lookup('env','http_proxy') }}"
  https_proxy: "{{ lookup('env','https_proxy') }}"
  HTTPS_PROXY: "{{ lookup('env','https_proxy') }}"
  no_proxy: "{{ lookup('env','no_proxy') }}"
  NO_PROXY: "{{ lookup('env','no_proxy') }}"

images: "{{ shared_images | combine(local_images | default({})) }}"

shared_images:
  shared/centos:
    version: "7.5.1804"
    method: build
    push: False
    required: {}
    directory: "{{ playbook_dir }}/../../shared-containers/centos/core"
  shared/centos/rpm-packer:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/rpm-packer"
    push: False
    args:
      USER_UID: "{{ user_id }}"
  shared/centos/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python36"
    push: False
  shared/centos/build-go:
    version: "1.10.2"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go"
    push: False
  shared/run/tensorflow/py2.7:
    version: "py2"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run/2.7"
    push: False
    args:
      PYTHON_VERSION: 2.7
  shared/run/tensorflow/py3.6:
    version: "py3"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run/3.6"
    push: False
    args:
      PYTHON_VERSION: 3.6
  shared/build/consul:
    version: "v1.1.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/consul"
    push: False
    fetch_files:
      - src: https://releases.hashicorp.com/consul/1.1.0/consul_1.1.0_linux_amd64.zip
        dest: consul-1.1.0_linux_amd64.zip
        checksum: 09c40c8b5be868003810064916d8460bff334ccfb59a5046390224b27e052c45
  shared/build/metrics:
    version: "0.0.1"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../applications/cli/experiment_metrics"
    push: False
