---

common_required:
  - iptables
  - libcgroup
  - libcgroup-tools
  - libcgroup-devel
  - selinux-policy >= 3.13.1-23
  - libseccomp-devel
  - libtool-ltdl-devel
  - policycoreutils-python
  - selinux-policy-targeted >= 3.13.1-102
  - selinux-policy-base >= 3.13.1-102
  - libffi-devel
  - byacc
  - gcc
  - gcc-c++
  - openssl-devel
  - openssl
  - vim
  - git
  - ebtables
  - byacc
  - cifs-utils
  - ebtables
  - ethtool
  - gcc
  - gcc-c++
  - git
  - iproute
  - iptables
  - iptables >= 1.4.21
  - libcgroup
  - libcgroup-devel
  - libcgroup-tools
  - libffi-devel
  - libseccomp-devel
  - libtool-ltdl-devel
  - make
  - nfs-utils
  - openssh
  - openssh-clients
  - openssl
  - openssl-devel
  - policycoreutils-python
  - python
  - python-backports
  - python-backports-ssl_match_hostname
  - python-devel
  - python-ipaddress
  - python-setuptools
  - rsync
  - selinux-policy >= 3.13.1-23
  - selinux-policy-base >= 3.13.1-102
  - selinux-policy-targeted >= 3.13.1-102
  - socat
  - systemd-libs
  - util-linux
  - vim
  - wget

local_images:
  rpm/python:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/python"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-pip-8.1.2-7.el7.noarch.rpm
        dest: python2-pip-8.1.2-7.el7.noarch.rpm
        checksum: 48a1e429a39599c8be0a5a7e8e31393dd43c0e97f53e3824a5d6652ba6c9a316
  rpm/docker:
    version: "18.03.1-ce"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/docker"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/docker-distribution:
    version: "2.6.2"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/docker-distribution"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm
        dest: docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm
        checksum: 52b2c48b9bb4d0d5357057127799e4d71129fe8997dd0f770a9fe68ee7f3eff0
  rpm/cni/rpm:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/cni/rpm"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/helm:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/helm"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes:
    version: "v1.10.11"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/prepare"
    push: False
  rpm/kubernetes/rpm/server:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/server"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/worker:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/worker"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/client:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/client"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/all:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/all"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/nginx/rpm:
    version: "1.13.9"
    required: {}
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/nginx"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.13.9-1.el7_4.ngx.x86_64.rpm
        dest: nginx-1.13.9-1.el7_4.ngx.x86_64.rpm
        checksum: 169be987c4a291ed8b9699da7c59f96700a0b178dcc55cd7dd835d4253128e07
  rpm/consul:
    version: "1.0.0"
    required:
      CONSUL_DATA_IMAGE: "shared/build/consul"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/consul/prepare"
    push: False
  rpm/consul/rpm:
    version: "1.0.0"
    required:
      BASE_IMAGE: "rpm/consul"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/consul/rpm"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
